# Generated by Django 4.2.23 on 2026-02-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registerbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion_prevista', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registerbooks.ejemplar')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.lector')),
            ],
        ),
    ]
